export const formations = [
    {
        icon: "topographie.png",
        title: "TOPOGRAPHIE",
        description: "Apprenez les techniques modernes de relevé et d'analyse de terrains, en utilisant des outils de géomatique et de cartographie numérique. Cette formation vous prépare aux métiers de la topographie avec une maîtrise complète des équipements de pointe",
        link: "topographie",
        full_description: "La topographie est une discipline scientifique qui s'intéresse à l'étude et à la représentation des formes et des caractéristiques d'un terrain, que ce soit à petite ou grande échelle. Elle implique la mesure précise des distances, des angles et des altitudes afin de dresser des plans détaillés ou des cartes géographiques. Cette science permet de comprendre la configuration du sol, qu'il s'agisse de montagnes, de vallées, de rivières, ou encore des structures artificielles telles que des bâtiments, des routes, ou des ponts. Pour réaliser ces mesures, les topographes utilisent des instruments sophistiqués comme le théodolite, le niveau optique, le GPS et la station totale, qui permettent de mesurer des coordonnées avec une grande précision. La topographie est essentielle dans divers domaines : en génie civil pour la construction de bâtiments et d'infrastructures, en urbanisme pour l'aménagement des villes, en agriculture pour la gestion des terrains, et dans la gestion des ressources naturelles pour comprendre l'impact des activités humaines sur l'environnement. En somme, elle joue un rôle clé dans la planification, la conception, et la réalisation de projets qui requièrent une compréhension fine du terrain.",
        debouches: "  Géomètre-topographe : Ce professionnel est chargé de réaliser des relevés topographiques et de dresser des plans précis de terrains pour la construction de routes, de bâtiments, et d'infrastructures. * Technicien en génie civil : Il travaille sur des projets de construction, aidant à planifier et à superviser la mise en œuvre des travaux grâce à des relevés topographiques. * Cartographe : Ce spécialiste crée des cartes en se basant sur des données topographiques, utiles dans l'urbanisme, l'environnement, et la gestion des territoires. * Ingénieur géomètre : Il participe à des projets de grande envergure, souvent en collaboration avec des architectes, des urbanistes, et des ingénieurs pour concevoir des infrastructures complexes. * Spécialiste en aménagement du territoire : Ce professionnel analyse les données topographiques pour planifier des projets de développement urbain ou rural, en optimisant l'utilisation des terres et des ressources. * Expert en systèmes d'information géographique (SIG) : Il combine la topographie avec des technologies informatiques pour analyser des données spatiales et aider à la prise de décision dans l'aménagement du territoire, la gestion environnementale, ou la planification urbaine. * Technicien en gestion des ressources naturelles : Les relevés topographiques sont essentiels pour la gestion des forêts, des rivières, et d'autres ressources naturelles, afin d'évaluer l'impact des activités humaines et de protéger l'environnement. * Consultant en travaux publics : Vous pouvez également évoluer en tant que consultant auprès des entreprises de travaux publics pour superviser et évaluer les relevés topographiques lors de la construction d’infrastructures majeures.",
        ues: "Info. Appliqué* Anglais professionnel* Droit du travail* Écrit professionnel* Topographie générale* Surface de référence et coordonnées* Planimétrie* Altimétrie"
    }
    ,
    {
        icon: "reseau.png",
        title: "MAINTENANCE ET RÉSEAU INFORMATIQUE",
        description: "Devenez un expert en maintenance informatique et en gestion de réseaux. Vous apprendrez à diagnostiquer et réparer des systèmes, ainsi qu’à installer, configurer et gérer des réseaux informatiques pour des entreprises de toutes tailles.",
        link: "maintenance-et-reseau-informatique",
        full_description: "La maintenance et réseau informatique est un domaine qui englobe l'ensemble des activités visant à assurer le bon fonctionnement des systèmes informatiques et des réseaux. Les professionnels dans ce domaine sont responsables de l'installation, de la configuration, de la surveillance et de la réparation des équipements informatiques tels que les ordinateurs, serveurs, routeurs, et autres infrastructures réseau.Leur rôle inclut la gestion des réseaux locaux (LAN), des réseaux étendus (WAN), et d'autres systèmes de communication, en veillant à ce que la connectivité soit fluide et sécurisée. Ils identifient et résolvent les problèmes techniques, effectuent des mises à jour régulières des logiciels et du matériel, et s'assurent que les systèmes de sécurité (pare-feu, antivirus, etc.) sont à jour pour protéger les données sensibles.Les techniciens et ingénieurs de ce domaine jouent un rôle crucial dans les entreprises, car ils garantissent la continuité des opérations en assurant que les systèmes informatiques fonctionnent efficacement. Ils peuvent aussi être amenés à former les utilisateurs sur les bonnes pratiques et à réaliser des audits de performance pour anticiper les besoins futurs en termes d’infrastructure.Les compétences acquises dans ce domaine permettent de travailler dans diverses industries, allant des PME aux grandes entreprises, dans des services IT internes ou en tant que consultant pour des prestataires spécialisés en maintenance informatique et gestion de réseaux.",
        debouches: " Technicien de maintenance informatique : Responsable de la réparation et de l’entretien des équipements informatiques. * Administrateur réseau : Gère et maintient les infrastructures réseau d’une entreprise. * Ingénieur en sécurité informatique : Assure la protection des systèmes informatiques et réseaux contre les cybermenaces. * Technicien support informatique : Fournit une assistance technique aux utilisateurs pour résoudre les problèmes matériels et logiciels. * Consultant en systèmes et réseaux : Conseille les entreprises sur l'optimisation et la gestion de leurs infrastructures réseau. * Architecte réseau : Conçoit et implémente les architectures réseau pour assurer une connectivité efficace et sécurisée. * Responsable IT : Supervise l’ensemble du parc informatique et des réseaux dans une organisation. * Ingénieur cloud : Gère les systèmes et réseaux basés sur des infrastructures cloud (Amazon AWS, Microsoft Azure, etc.).",
        ues: "Maintenance technique et logistique* Réseau informatique* Système de vidéo surveillance* Antenne parabolique"

    },
    {
        icon: "vente.png",
        title: "VENTE ET GESTION DE CAISSE",
        description: "Acquérez les compétences nécessaires pour travailler dans la vente au détail et la gestion des opérations de caisse. Cette formation vous prépare à la gestion des transactions commerciales, des inventaires et des relations clients.",
        link: "vente-et-gestion-de-caisse",
        full_description: "La vente et gestion de caisse est un domaine qui regroupe l'ensemble des compétences nécessaires pour assurer une expérience client fluide et efficace lors des transactions commerciales, tout en garantissant une bonne gestion des opérations financières liées aux points de vente. Cette formation prépare à la maîtrise des outils et des techniques utilisés dans les commerces pour gérer les ventes, encaisser les paiements, et optimiser la gestion des stocks.Les professionnels dans ce secteur sont responsables de l’accueil des clients, de la présentation des produits, et de la finalisation des ventes. Ils doivent connaître les différents modes de paiement (espèces, cartes, chèques, etc.) et utiliser des logiciels de gestion de caisse (POS - Point of Sale). Leur rôle inclut également la gestion des transactions (ouvertures et fermetures de caisse), la vérification des fonds de caisse, et le traitement des anomalies ou des écarts.En plus de la gestion des opérations quotidiennes, ils assurent aussi une bonne organisation des stocks en collaboration avec d'autres équipes, veillant à ce que les produits soient disponibles et bien exposés. Les compétences en vente incluent la capacité à comprendre les besoins des clients, à conseiller sur les produits et à garantir une satisfaction maximale pour favoriser la fidélité.Ce domaine forme des professionnels qui sont à l’aise avec l’utilisation des outils informatiques et possèdent d'excellentes compétences relationnelles. Ils sont essentiels dans des environnements variés tels que les commerces de détail, les grandes surfaces, les boutiques spécialisées ou encore les environnements de restauration et de services.",
        debouches: " Caissier : Gère les transactions de vente et assure l’encaissement des paiements. * Responsable de caisse : Supervise l’activité des caissiers et gère les fonds de caisse. * Vendeur en magasin : Conseille les clients, effectue les ventes et assure la satisfaction client. * Gestionnaire de point de vente : S’occupe de la gestion globale du magasin, y compris les ventes, les stocks et la caisse. * Assistant commercial : Aide à la gestion des ventes et des relations avec les clients. * Responsable de magasin : Gère les opérations commerciales, l’équipe de vente et la gestion de la caisse. * Technicien en maintenance de systèmes de caisse : Assure le bon fonctionnement des terminaux de point de vente (POS). * Formateur en systèmes de caisse : Forme les employés à l’utilisation des logiciels et systèmes de gestion de caisse.",
        ues: "Info. Bureautique* TypingMaster* Anglais Professionnel* Droit du travail* Écrit Professionnel* Communication* Compta. Général* Sage 100 Commercial* Compatibilité* Caisse décentralisée"
    },
    {
        icon: "transi.png",
        title: "TRANSI DOUANE & MAGASINAGE",
        description: "Cette formation vous prépare à gérer les processus de transit douanier et de magasinage. Apprenez à assurer le suivi des marchandises, à maîtriser les procédures douanières et à organiser les flux logistiques de manière optimale.",
        link: "transi-douane-magasinage",
        full_description: "Le transit douanier et le magasinage sont deux processus clés dans la logistique internationale et la gestion des chaînes d'approvisionnement. Le transit douanier fait référence au processus par lequel les marchandises traversent les frontières internationales en respectant les régulations douanières. Cela inclut la déclaration des biens aux autorités douanières, le paiement des droits de douane et des taxes, ainsi que la vérification et l'inspection des marchandises pour s'assurer qu'elles sont conformes aux réglementations des pays d'origine, de transit et de destination. Une gestion efficace du transit douanier permet d'éviter des retards et des pénalités, facilitant ainsi le commerce international.Le magasinage, de son côté, concerne la gestion et le stockage des marchandises dans un entrepôt ou un centre de distribution. Il comprend la réception des produits, leur rangement selon des systèmes d'organisation adaptés, la gestion des niveaux de stocks pour éviter les ruptures ou les excédents, et la préparation des commandes en vue de leur expédition. Une gestion efficace du magasinage optimise l'espace de stockage, réduit les coûts opérationnels et assure que les marchandises sont disponibles en bon état et en temps opportun pour répondre à la demande. Ensemble, ces processus assurent une chaîne d'approvisionnement fluide et conforme aux exigences réglementaires.",
        debouches: " Transit douanier : Gère les formalités douanières pour le passage des marchandises à travers les frontières. * Déclarant en douane : Prépare et soumet les déclarations douanières nécessaires pour l'importation ou l'exportation de marchandises. * Responsable douanier : Supervise les opérations douanières, veille à la conformité avec les réglementations et gère les relations avec les autorités douanières. * Contrôleur de conformité : Vérifie que les marchandises et la documentation respectent les réglementations douanières et les normes internationales. * Agent de transit : Organise et coordonne le transport des marchandises à travers les frontières, en s'assurant que toutes les formalités douanières sont remplies. * Expert en réglementation douanière : Conseille les entreprises sur les règles et les procédures douanières pour optimiser le transit des marchandises. * Gestionnaire de chaîne d'approvisionnement : Supervise l'ensemble du processus de transit douanier et de gestion des stocks pour garantir une chaîne d'approvisionnement fluide.*Magasinage : Gère le stockage et la gestion des marchandises dans un entrepôt ou un centre de distribution. * Responsable d'entrepôt : Supervise les opérations de stockage, de gestion des stocks et de préparation des commandes. * Gestionnaire de stocks : Assure la gestion et le suivi des niveaux de stocks pour optimiser l'approvisionnement et réduire les excédents. * Préparateur de commandes : Prépare les marchandises pour l'expédition en fonction des commandes reçues, en veillant à leur précision et à leur bon état. * Coordinateur de logistique : Organise le transport et le stockage des marchandises, en coordonnant les activités entre les différents services logistiques. * Opérateur de chariot élévateur : Manie les équipements de levage pour déplacer les marchandises au sein de l'entrepôt. * Analyste des opérations de stockage : Évalue les processus de gestion des stocks et propose des améliorations pour optimiser l'efficacité de l'entrepôt. * Responsable de la qualité : Veille à ce que les marchandises stockées répondent aux normes de qualité avant leur expédition.",
        ues: "Info. Appliquée * Anglais * professionnel * Droit du travail * Écrit professionnel * Transi-douane * consignation * Négoce * Transport logistique * Entreposage"
    },
    {
        icon: "langue.png",
        title: "LANGUES",
        description: "Améliorez vos compétences linguistiques dans des langues clés pour le commerce international et les affaires. Nous proposons des formations adaptées aux besoins professionnels, avec des cours intensifs en anglais, espagnole, français et autres langues.",
        link: "langues",
        full_description: "La formation en langues couvre l'anglais, l'espagnol et le français, visant à développer des compétences linguistiques complètes pour faciliter la communication dans divers contextes professionnels et personnels. En anglais, la formation se concentre sur la grammaire, le vocabulaire, les compétences orales et écrites, ainsi que la compréhension orale et la communication interculturelle, essentielle pour les interactions internationales. En espagnol, elle inclut l'étude de la grammaire, la pratique de la conversation, la rédaction de documents professionnels, la compréhension orale, et une sensibilisation aux aspects culturels des pays hispanophones. En français, la formation couvre également la grammaire et le vocabulaire, les compétences orales et écrites, la compréhension orale, et la culture francophone, afin de maîtriser les nuances linguistiques et culturelles dans les interactions professionnelles et sociales. Cette approche globale permet de renforcer les capacités de communication et de compréhension dans ces trois langues majeures.",
        debouches: " Formation en langues (Anglais, Espagnol, Français) : * Traducteur : Convertit des documents et des communications d'une langue à une autre, assurant la précision et la fluidité du texte. * Interprète : Facilite la communication orale entre des personnes parlant différentes langues lors de conférences, réunions ou événements. * Enseignant de langues : Enseigne l'anglais, l'espagnol ou le français dans des écoles, des instituts de langue ou des programmes de formation. * Rédacteur/trice : Crée et édite des contenus écrits dans plusieurs langues pour des publications, des sites web ou des documents marketing. * Responsable de la communication internationale : Gère les relations et les échanges internationaux dans un environnement professionnel, en utilisant plusieurs langues pour assurer une communication efficace. * Conseiller en affaires internationales : Offre des conseils sur les stratégies de marché et les négociations dans des contextes multilingues. * Agent de service clientèle multilingue : Fournit un support client dans plusieurs langues, améliorant la satisfaction et l'expérience client. * Spécialiste en localisation : Adapte des produits, services ou contenus pour les rendre appropriés aux marchés francophones, hispanophones ou anglophones.",
        ues: "Non precisé"
    }
]